// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 33: // ['!','!']
			return 2
		case r == 35: // ['#','#']
			return 3
		case r == 37: // ['%','%']
			return 4
		case r == 39: // [''',''']
			return 5
		case r == 40: // ['(','(']
			return 6
		case r == 41: // [')',')']
			return 7
		case r == 42: // ['*','*']
			return 4
		case r == 43: // ['+','+']
			return 4
		case r == 44: // [',',',']
			return 8
		case r == 45: // ['-','-']
			return 4
		case r == 47: // ['/','/']
			return 4
		case 48 <= r && r <= 57: // ['0','9']
			return 9
		case r == 58: // [':',':']
			return 10
		case r == 60: // ['<','<']
			return 11
		case r == 61: // ['=','=']
			return 12
		case r == 62: // ['>','>']
			return 13
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case r == 91: // ['[','[']
			return 15
		case r == 93: // [']',']']
			return 16
		case r == 97: // ['a','a']
			return 14
		case r == 98: // ['b','b']
			return 17
		case r == 99: // ['c','c']
			return 18
		case 100 <= r && r <= 101: // ['d','e']
			return 14
		case r == 102: // ['f','f']
			return 19
		case 103 <= r && r <= 109: // ['g','m']
			return 14
		case r == 110: // ['n','n']
			return 20
		case 111 <= r && r <= 115: // ['o','s']
			return 14
		case r == 116: // ['t','t']
			return 21
		case 117 <= r && r <= 122: // ['u','z']
			return 14
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 22
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 23
		case 65 <= r && r <= 90: // ['A','Z']
			return 24
		case 97 <= r && r <= 122: // ['a','z']
			return 24
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 46: // ['.','.']
			return 25
		case 48 <= r && r <= 57: // ['0','9']
			return 9
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case r == 58: // [':',':']
			return 26
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 22
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 22
		case r == 62: // ['>','>']
			return 27
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 61: // ['=','=']
			return 22
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 122: // ['a','z']
			return 14
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 110: // ['a','n']
			return 14
		case r == 111: // ['o','o']
			return 29
		case 112 <= r && r <= 122: // ['p','z']
			return 14
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 103: // ['a','g']
			return 14
		case r == 104: // ['h','h']
			return 30
		case 105 <= r && r <= 122: // ['i','z']
			return 14
		}
		return NoState
	},
	// S19
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case r == 97: // ['a','a']
			return 31
		case 98 <= r && r <= 122: // ['b','z']
			return 14
		}
		return NoState
	},
	// S20
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 116: // ['a','t']
			return 14
		case r == 117: // ['u','u']
			return 32
		case 118 <= r && r <= 122: // ['v','z']
			return 14
		}
		return NoState
	},
	// S21
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 113: // ['a','q']
			return 14
		case r == 114: // ['r','r']
			return 33
		case 115 <= r && r <= 122: // ['s','z']
			return 14
		}
		return NoState
	},
	// S22
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S23
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 34
		}
		return NoState
	},
	// S24
	func(r rune) int {
		switch {
		case r == 39: // [''',''']
			return 34
		}
		return NoState
	},
	// S25
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		}
		return NoState
	},
	// S26
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S27
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S28
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 122: // ['a','z']
			return 14
		}
		return NoState
	},
	// S29
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 110: // ['a','n']
			return 14
		case r == 111: // ['o','o']
			return 36
		case 112 <= r && r <= 122: // ['p','z']
			return 14
		}
		return NoState
	},
	// S30
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case r == 97: // ['a','a']
			return 37
		case 98 <= r && r <= 122: // ['b','z']
			return 14
		}
		return NoState
	},
	// S31
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 107: // ['a','k']
			return 14
		case r == 108: // ['l','l']
			return 38
		case 109 <= r && r <= 122: // ['m','z']
			return 14
		}
		return NoState
	},
	// S32
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 108: // ['a','l']
			return 14
		case r == 109: // ['m','m']
			return 39
		case 110 <= r && r <= 122: // ['n','z']
			return 14
		}
		return NoState
	},
	// S33
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 116: // ['a','t']
			return 14
		case r == 117: // ['u','u']
			return 40
		case 118 <= r && r <= 122: // ['v','z']
			return 14
		}
		return NoState
	},
	// S34
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S35
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 35
		}
		return NoState
	},
	// S36
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 107: // ['a','k']
			return 14
		case r == 108: // ['l','l']
			return 41
		case 109 <= r && r <= 122: // ['m','z']
			return 14
		}
		return NoState
	},
	// S37
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 113: // ['a','q']
			return 14
		case r == 114: // ['r','r']
			return 42
		case 115 <= r && r <= 122: // ['s','z']
			return 14
		}
		return NoState
	},
	// S38
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 114: // ['a','r']
			return 14
		case r == 115: // ['s','s']
			return 43
		case 116 <= r && r <= 122: // ['t','z']
			return 14
		}
		return NoState
	},
	// S39
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 122: // ['a','z']
			return 14
		}
		return NoState
	},
	// S40
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 100: // ['a','d']
			return 14
		case r == 101: // ['e','e']
			return 44
		case 102 <= r && r <= 122: // ['f','z']
			return 14
		}
		return NoState
	},
	// S41
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 122: // ['a','z']
			return 14
		}
		return NoState
	},
	// S42
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 122: // ['a','z']
			return 14
		}
		return NoState
	},
	// S43
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 100: // ['a','d']
			return 14
		case r == 101: // ['e','e']
			return 45
		case 102 <= r && r <= 122: // ['f','z']
			return 14
		}
		return NoState
	},
	// S44
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 122: // ['a','z']
			return 14
		}
		return NoState
	},
	// S45
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 28
		case 65 <= r && r <= 90: // ['A','Z']
			return 14
		case 97 <= r && r <= 122: // ['a','z']
			return 14
		}
		return NoState
	},
}
