// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: List
			nil,       // empty
			shift(6),  // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // empty
			nil,          // id
			nil,          // ::
			nil,          // =>
			nil,          // (
			nil,          // )
			nil,          // ,
			nil,          // num
			nil,          // bool
			nil,          // char
			nil,          // [
			nil,          // ]
			nil,          // plusminus
			nil,          // multdiv
			nil,          // \\
			nil,          // boolean
			nil,          // number
			nil,          // charac
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Program
			nil,       // empty
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(3), // $, reduce: List
			nil,       // empty
			shift(6),  // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(4), // $, reduce: FunctionOrCall
			nil,       // empty
			reduce(4), // id, reduce: FunctionOrCall
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(5), // $, reduce: FunctionOrCall
			nil,       // empty
			reduce(5), // id, reduce: FunctionOrCall
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // empty
			nil,      // id
			shift(8), // ::
			nil,      // =>
			shift(9), // (
			nil,      // )
			nil,      // ,
			nil,      // num
			nil,      // bool
			nil,      // char
			nil,      // [
			nil,      // ]
			nil,      // plusminus
			nil,      // multdiv
			nil,      // \\
			nil,      // boolean
			nil,      // number
			nil,      // charac
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(2), // $, reduce: List
			nil,       // empty
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			reduce(9), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			shift(12), // num
			shift(13), // bool
			shift(14), // char
			shift(15), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			shift(17),  // id
			nil,        // ::
			nil,        // =>
			shift(18),  // (
			reduce(29), // ), reduce: Args
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(20),  // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			shift(28),  // boolean
			shift(29),  // number
			shift(30),  // charac
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			shift(31), // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(32), // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(10), // id, reduce: Type
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(11), // id, reduce: Type
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(12), // id, reduce: Type
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			shift(34), // num
			shift(35), // bool
			shift(36), // char
			shift(37), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(14), // ), reduce: Statement
			reduce(14), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(14), // plusminus, reduce: Statement
			reduce(14), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(38),  // (
			reduce(18), // ), reduce: Statement
			reduce(18), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(18), // plusminus, reduce: Statement
			reduce(18), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(40), // id
			nil,       // ::
			nil,       // =>
			shift(41), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(43), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			shift(49), // \\
			shift(50), // boolean
			shift(51), // number
			shift(52), // charac
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(24), // ), reduce: Factor
			reduce(24), // ,, reduce: Factor
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(24), // plusminus, reduce: Factor
			reduce(24), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			shift(54),  // id
			nil,        // ::
			nil,        // =>
			shift(55),  // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(57),  // [
			reduce(29), // ], reduce: Args
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			shift(65),  // boolean
			shift(66),  // number
			shift(67),  // charac
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(15), // ), reduce: Statement
			reduce(15), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(15), // plusminus, reduce: Statement
			reduce(15), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(16), // ), reduce: Statement
			reduce(16), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			shift(68),  // plusminus
			reduce(16), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(17), // ), reduce: Statement
			reduce(17), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(17), // plusminus, reduce: Statement
			reduce(17), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(20), // ), reduce: Expression
			reduce(20), // ,, reduce: Expression
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(20), // plusminus, reduce: Expression
			shift(69),  // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(22), // ), reduce: Term
			reduce(22), // ,, reduce: Term
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(22), // plusminus, reduce: Term
			reduce(22), // multdiv, reduce: Term
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			shift(70), // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(28), // ), reduce: Args
			shift(71),  // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(32), // ), reduce: Constant
			reduce(32), // ,, reduce: Constant
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(32), // plusminus, reduce: Constant
			reduce(32), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(33), // ), reduce: Constant
			reduce(33), // ,, reduce: Constant
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(33), // plusminus, reduce: Constant
			reduce(33), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(34), // ), reduce: Constant
			reduce(34), // ,, reduce: Constant
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(34), // plusminus, reduce: Constant
			reduce(34), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			nil,       // =>
			shift(72), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			reduce(8), // =>, reduce: Params
			nil,       // (
			nil,       // )
			shift(73), // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			shift(74), // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(10), // ], reduce: Type
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(11), // ], reduce: Type
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(12), // ], reduce: Type
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			shift(34), // num
			shift(35), // bool
			shift(36), // char
			shift(37), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			shift(17),  // id
			nil,        // ::
			nil,        // =>
			shift(18),  // (
			reduce(29), // ), reduce: Args
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(20),  // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			shift(28),  // boolean
			shift(29),  // number
			shift(30),  // charac
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(14), // ), reduce: Statement
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(14), // plusminus, reduce: Statement
			reduce(14), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(77),  // (
			reduce(18), // ), reduce: Statement
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(18), // plusminus, reduce: Statement
			reduce(18), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(40), // id
			nil,       // ::
			nil,       // =>
			shift(41), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(43), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			shift(79), // \\
			shift(50), // boolean
			shift(51), // number
			shift(52), // charac
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(24), // ), reduce: Factor
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(24), // plusminus, reduce: Factor
			reduce(24), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			shift(54),  // id
			nil,        // ::
			nil,        // =>
			shift(55),  // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(57),  // [
			reduce(29), // ], reduce: Args
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			shift(65),  // boolean
			shift(66),  // number
			shift(67),  // charac
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(15), // ), reduce: Statement
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(15), // plusminus, reduce: Statement
			reduce(15), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(81),  // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			shift(82),  // plusminus
			reduce(16), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(17), // ), reduce: Statement
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(17), // plusminus, reduce: Statement
			reduce(17), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(20), // ), reduce: Expression
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(20), // plusminus, reduce: Expression
			shift(83),  // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(22), // ), reduce: Term
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(22), // plusminus, reduce: Term
			reduce(22), // multdiv, reduce: Term
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			reduce(9), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			shift(12), // num
			shift(13), // bool
			shift(14), // char
			shift(15), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(32), // ), reduce: Constant
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(32), // plusminus, reduce: Constant
			reduce(32), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(33), // ), reduce: Constant
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(33), // plusminus, reduce: Constant
			reduce(33), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(34), // ), reduce: Constant
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(34), // plusminus, reduce: Constant
			reduce(34), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(14), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(14), // ], reduce: Statement
			reduce(14), // plusminus, reduce: Statement
			reduce(14), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(85),  // (
			nil,        // )
			reduce(18), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(18), // ], reduce: Statement
			reduce(18), // plusminus, reduce: Statement
			reduce(18), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(40), // id
			nil,       // ::
			nil,       // =>
			shift(41), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(43), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			shift(87), // \\
			shift(50), // boolean
			shift(51), // number
			shift(52), // charac
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(24), // ,, reduce: Factor
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(24), // ], reduce: Factor
			reduce(24), // plusminus, reduce: Factor
			reduce(24), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			shift(54),  // id
			nil,        // ::
			nil,        // =>
			shift(55),  // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(57),  // [
			reduce(29), // ], reduce: Args
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			shift(65),  // boolean
			shift(66),  // number
			shift(67),  // charac
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(15), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(15), // ], reduce: Statement
			reduce(15), // plusminus, reduce: Statement
			reduce(15), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(16), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(16), // ], reduce: Statement
			shift(89),  // plusminus
			reduce(16), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(17), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(17), // ], reduce: Statement
			reduce(17), // plusminus, reduce: Statement
			reduce(17), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(20), // ,, reduce: Expression
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(20), // ], reduce: Expression
			reduce(20), // plusminus, reduce: Expression
			shift(90),  // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(22), // ,, reduce: Term
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(22), // ], reduce: Term
			reduce(22), // plusminus, reduce: Term
			reduce(22), // multdiv, reduce: Term
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			shift(91), // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			shift(92),  // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(28), // ], reduce: Args
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(32), // ,, reduce: Constant
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(32), // ], reduce: Constant
			reduce(32), // plusminus, reduce: Constant
			reduce(32), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(33), // ,, reduce: Constant
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(33), // ], reduce: Constant
			reduce(33), // plusminus, reduce: Constant
			reduce(33), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(34), // ,, reduce: Constant
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(34), // ], reduce: Constant
			reduce(34), // plusminus, reduce: Constant
			reduce(34), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(17), // id
			nil,       // ::
			nil,       // =>
			shift(18), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(20), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			shift(28), // boolean
			shift(29), // number
			shift(30), // charac
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(17), // id
			nil,       // ::
			nil,       // =>
			shift(18), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(20), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			shift(28), // boolean
			shift(29), // number
			shift(30), // charac
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(25), // $, reduce: FunctionCall
			nil,        // empty
			reduce(25), // id, reduce: FunctionCall
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			shift(17),  // id
			nil,        // ::
			nil,        // =>
			shift(18),  // (
			reduce(29), // ), reduce: Args
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(20),  // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			shift(28),  // boolean
			shift(29),  // number
			shift(30),  // charac
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(40), // id
			nil,       // ::
			nil,       // =>
			shift(41), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(43), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			shift(50), // boolean
			shift(51), // number
			shift(52), // charac
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			reduce(9), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			shift(12), // num
			shift(13), // bool
			shift(14), // char
			shift(15), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			reduce(13), // id, reduce: Type
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			shift(101), // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(102), // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			shift(17),  // id
			nil,        // ::
			nil,        // =>
			shift(18),  // (
			reduce(29), // ), reduce: Args
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(20),  // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			shift(28),  // boolean
			shift(29),  // number
			shift(30),  // charac
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(104), // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			shift(82),  // plusminus
			reduce(16), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			reduce(9), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			shift(12), // num
			shift(13), // bool
			shift(14), // char
			shift(15), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			shift(106), // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(23), // ), reduce: Factor
			reduce(23), // ,, reduce: Factor
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(23), // plusminus, reduce: Factor
			reduce(23), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(40), // id
			nil,       // ::
			nil,       // =>
			shift(41), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(43), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			shift(50), // boolean
			shift(51), // number
			shift(52), // charac
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(40), // id
			nil,       // ::
			nil,       // =>
			shift(41), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(43), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			shift(50), // boolean
			shift(51), // number
			shift(52), // charac
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			shift(109), // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			shift(17),  // id
			nil,        // ::
			nil,        // =>
			shift(18),  // (
			reduce(29), // ), reduce: Args
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(20),  // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			shift(28),  // boolean
			shift(29),  // number
			shift(30),  // charac
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(111), // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			shift(82),  // plusminus
			reduce(16), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			reduce(9), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			shift(12), // num
			shift(13), // bool
			shift(14), // char
			shift(15), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			shift(113), // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(54), // id
			nil,       // ::
			nil,       // =>
			shift(55), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(57), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			shift(65), // boolean
			shift(66), // number
			shift(67), // charac
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(54), // id
			nil,       // ::
			nil,       // =>
			shift(55), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(57), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			shift(65), // boolean
			shift(66), // number
			shift(67), // charac
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(35), // ), reduce: Constant
			reduce(35), // ,, reduce: Constant
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(35), // plusminus, reduce: Constant
			reduce(35), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			shift(54),  // id
			nil,        // ::
			nil,        // =>
			shift(55),  // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(57),  // [
			reduce(29), // ], reduce: Args
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			shift(65),  // boolean
			shift(66),  // number
			shift(67),  // charac
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(24), // ), reduce: Factor
			reduce(24), // ,, reduce: Factor
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(24), // plusminus, reduce: Factor
			reduce(24), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(17), // ), reduce: Statement
			reduce(17), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(17), // plusminus, reduce: Statement
			reduce(17), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(19), // ), reduce: Expression
			reduce(19), // ,, reduce: Expression
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(19), // plusminus, reduce: Expression
			shift(69),  // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(21), // ), reduce: Term
			reduce(21), // ,, reduce: Term
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(21), // plusminus, reduce: Term
			reduce(21), // multdiv, reduce: Term
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(27), // ), reduce: Args
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(119), // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(24), // plusminus, reduce: Factor
			reduce(24), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S99
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(16), // ), reduce: Statement
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			shift(82),  // plusminus
			reduce(16), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S100
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			nil,       // id
			nil,       // ::
			reduce(7), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S101
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(13), // ], reduce: Type
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S102
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(25), // ), reduce: FunctionCall
			reduce(25), // ,, reduce: FunctionCall
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(25), // plusminus, reduce: FunctionCall
			reduce(25), // multdiv, reduce: FunctionCall
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S103
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(120), // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S104
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(23), // ), reduce: Factor
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(23), // plusminus, reduce: Factor
			reduce(23), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S105
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			shift(121), // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S106
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(35), // ), reduce: Constant
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(35), // plusminus, reduce: Constant
			reduce(35), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S107
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(19), // ), reduce: Expression
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(19), // plusminus, reduce: Expression
			shift(83),  // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S108
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(21), // ), reduce: Term
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(21), // plusminus, reduce: Term
			reduce(21), // multdiv, reduce: Term
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S109
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(40), // id
			nil,       // ::
			nil,       // =>
			shift(41), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(43), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			shift(50), // boolean
			shift(51), // number
			shift(52), // charac
		},
	},
	actionRow{ // S110
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(123), // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S111
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(23), // ,, reduce: Factor
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(23), // ], reduce: Factor
			reduce(23), // plusminus, reduce: Factor
			reduce(23), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S112
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			shift(124), // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S113
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(35), // ,, reduce: Constant
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(35), // ], reduce: Constant
			reduce(35), // plusminus, reduce: Constant
			reduce(35), // multdiv, reduce: Constant
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S114
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(24), // ,, reduce: Factor
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(24), // ], reduce: Factor
			reduce(24), // plusminus, reduce: Factor
			reduce(24), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S115
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(17), // ,, reduce: Statement
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(17), // ], reduce: Statement
			reduce(17), // plusminus, reduce: Statement
			reduce(17), // multdiv, reduce: Statement
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S116
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(19), // ,, reduce: Expression
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(19), // ], reduce: Expression
			reduce(19), // plusminus, reduce: Expression
			shift(90),  // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S117
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(21), // ,, reduce: Term
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(21), // ], reduce: Term
			reduce(21), // plusminus, reduce: Term
			reduce(21), // multdiv, reduce: Term
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S118
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(27), // ], reduce: Args
			nil,        // plusminus
			nil,        // multdiv
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S119
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(6), // $, reduce: Function
			nil,       // empty
			reduce(6), // id, reduce: Function
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S120
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(25), // ), reduce: FunctionCall
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(25), // plusminus, reduce: FunctionCall
			reduce(25), // multdiv, reduce: FunctionCall
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S121
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(40), // id
			nil,       // ::
			nil,       // =>
			shift(41), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(43), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			shift(50), // boolean
			shift(51), // number
			shift(52), // charac
		},
	},
	actionRow{ // S122
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(126), // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(24), // plusminus, reduce: Factor
			reduce(24), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S123
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(25), // ,, reduce: FunctionCall
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(25), // ], reduce: FunctionCall
			reduce(25), // plusminus, reduce: FunctionCall
			reduce(25), // multdiv, reduce: FunctionCall
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S124
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // empty
			shift(40), // id
			nil,       // ::
			nil,       // =>
			shift(41), // (
			nil,       // )
			nil,       // ,
			nil,       // num
			nil,       // bool
			nil,       // char
			shift(43), // [
			nil,       // ]
			nil,       // plusminus
			nil,       // multdiv
			nil,       // \\
			shift(50), // boolean
			shift(51), // number
			shift(52), // charac
		},
	},
	actionRow{ // S125
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(128), // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(24), // plusminus, reduce: Factor
			reduce(24), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S126
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(26), // ), reduce: Lambda
			reduce(26), // ,, reduce: Lambda
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(26), // plusminus, reduce: Lambda
			reduce(26), // multdiv, reduce: Lambda
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S127
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(129), // )
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(24), // plusminus, reduce: Factor
			reduce(24), // multdiv, reduce: Factor
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S128
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(26), // ), reduce: Lambda
			nil,        // ,
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			reduce(26), // plusminus, reduce: Lambda
			reduce(26), // multdiv, reduce: Lambda
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S129
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // empty
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(26), // ,, reduce: Lambda
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(26), // ], reduce: Lambda
			reduce(26), // plusminus, reduce: Lambda
			reduce(26), // multdiv, reduce: Lambda
			nil,        // \\
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
}
