// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			shift(4), // func
			nil,      // id
			nil,      // ::
			nil,      // =>
			nil,      // (
			nil,      // )
			nil,      // ,
			nil,      // empty
			nil,      // num
			nil,      // bool
			nil,      // char
			nil,      // [
			nil,      // ]
			nil,      // operations
			nil,      // relop
			nil,      // #
			nil,      // boolean
			nil,      // number
			nil,      // charac
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          // INVALID
			accept(true), // $
			nil,          // func
			nil,          // id
			nil,          // ::
			nil,          // =>
			nil,          // (
			nil,          // )
			nil,          // ,
			nil,          // empty
			nil,          // num
			nil,          // bool
			nil,          // char
			nil,          // [
			nil,          // ]
			nil,          // operations
			nil,          // relop
			nil,          // #
			nil,          // boolean
			nil,          // number
			nil,          // charac
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      // INVALID
			nil,      // $
			nil,      // func
			shift(6), // id
			nil,      // ::
			nil,      // =>
			nil,      // (
			nil,      // )
			nil,      // ,
			nil,      // empty
			nil,      // num
			nil,      // bool
			nil,      // char
			nil,      // [
			nil,      // ]
			shift(7), // operations
			shift(8), // relop
			nil,      // #
			nil,      // boolean
			nil,      // number
			nil,      // charac
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			shift(4),  // func
			reduce(3), // id, reduce: Functions
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			reduce(3), // operations, reduce: Functions
			reduce(3), // relop, reduce: Functions
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			shift(10), // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			reduce(1), // $, reduce: Program
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			shift(11), // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			shift(12), // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			shift(13), // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			reduce(2), // id, reduce: Functions
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			reduce(2), // operations, reduce: Functions
			reduce(2), // relop, reduce: Functions
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			shift(14), // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			reduce(7), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			shift(33), // num
			shift(34), // bool
			shift(35), // char
			shift(36), // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(15), // ), reduce: Statement
			reduce(15), // ,, reduce: Statement
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(37),  // (
			reduce(12), // ), reduce: Statement
			reduce(12), // ,, reduce: Statement
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			shift(38), // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(23), // ), reduce: Args
			shift(39),  // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(41),  // id
			nil,        // ::
			nil,        // =>
			shift(42),  // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(44),  // [
			reduce(24), // ], reduce: Args
			shift(48),  // operations
			shift(49),  // relop
			nil,        // #
			shift(51),  // boolean
			shift(52),  // number
			shift(53),  // charac
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(13), // ), reduce: Statement
			reduce(13), // ,, reduce: Statement
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(14), // ), reduce: Statement
			reduce(14), // ,, reduce: Statement
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			shift(54), // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			shift(55), // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			shift(56), // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(57),  // (
			reduce(19), // ), reduce: LambdaExpr
			reduce(19), // ,, reduce: LambdaExpr
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(25), // ), reduce: Constant
			reduce(25), // ,, reduce: Constant
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(26), // ), reduce: Constant
			reduce(26), // ,, reduce: Constant
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(27), // ), reduce: Constant
			reduce(27), // ,, reduce: Constant
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			shift(58), // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			shift(59), // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			shift(60), // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			shift(61), // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			reduce(8), // id, reduce: Type
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			reduce(9), // id, reduce: Type
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			reduce(10), // id, reduce: Type
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			shift(63), // num
			shift(64), // bool
			shift(65), // char
			shift(66), // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			reduce(7), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			shift(33), // num
			shift(34), // bool
			shift(35), // char
			shift(36), // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(15), // ,, reduce: Statement
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(15), // ], reduce: Statement
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(70),  // (
			nil,        // )
			reduce(12), // ,, reduce: Statement
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(12), // ], reduce: Statement
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			shift(71), // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			shift(72),  // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(23), // ], reduce: Args
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(41),  // id
			nil,        // ::
			nil,        // =>
			shift(42),  // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(44),  // [
			reduce(24), // ], reduce: Args
			shift(48),  // operations
			shift(49),  // relop
			nil,        // #
			shift(51),  // boolean
			shift(52),  // number
			shift(53),  // charac
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(13), // ,, reduce: Statement
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(13), // ], reduce: Statement
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(14), // ,, reduce: Statement
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(14), // ], reduce: Statement
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			shift(74), // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			shift(75), // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			shift(76), // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(77),  // (
			nil,        // )
			reduce(19), // ,, reduce: LambdaExpr
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(19), // ], reduce: LambdaExpr
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(25), // ,, reduce: Constant
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(25), // ], reduce: Constant
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(26), // ,, reduce: Constant
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(26), // ], reduce: Constant
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(27), // ,, reduce: Constant
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(27), // ], reduce: Constant
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(16), // $, reduce: FunctionCall
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S57
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S58
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(17), // $, reduce: FunctionCall
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S59
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			reduce(18), // $, reduce: FunctionCall
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S60
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			shift(82), // num
			shift(83), // bool
			shift(84), // char
			shift(85), // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S61
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			reduce(6), // =>, reduce: Params
			nil,       // (
			nil,       // )
			shift(86), // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S62
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			shift(87), // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S63
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			reduce(8), // ], reduce: Type
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S64
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			reduce(9), // ], reduce: Type
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S65
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(10), // ], reduce: Type
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S66
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			shift(63), // num
			shift(64), // bool
			shift(65), // char
			shift(66), // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S67
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			shift(89), // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S68
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			shift(90), // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S69
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(22), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S70
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S71
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			reduce(7), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			shift(33), // num
			shift(34), // bool
			shift(35), // char
			shift(36), // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S72
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(41),  // id
			nil,        // ::
			nil,        // =>
			shift(42),  // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(44),  // [
			reduce(24), // ], reduce: Args
			shift(48),  // operations
			shift(49),  // relop
			nil,        // #
			shift(51),  // boolean
			shift(52),  // number
			shift(53),  // charac
		},
	},
	actionRow{ // S73
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			shift(94), // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S74
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(28), // ), reduce: Constant
			reduce(28), // ,, reduce: Constant
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S75
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S76
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S77
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S78
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			shift(98), // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S79
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			shift(99), // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S80
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(100), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S81
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(101), // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S82
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			reduce(8), // (, reduce: Type
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S83
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			reduce(9), // (, reduce: Type
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S84
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			reduce(10), // (, reduce: Type
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S85
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			shift(63), // num
			shift(64), // bool
			shift(65), // char
			shift(66), // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S86
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			reduce(7), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			shift(33), // num
			shift(34), // bool
			shift(35), // char
			shift(36), // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S87
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			reduce(11), // id, reduce: Type
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S88
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			shift(104), // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S89
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(16), // ), reduce: FunctionCall
			reduce(16), // ,, reduce: FunctionCall
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S90
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(105), // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S91
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(106), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S92
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			shift(107), // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S93
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(22), // ], reduce: Args
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S94
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(28), // ,, reduce: Constant
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(28), // ], reduce: Constant
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S95
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(108), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S96
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(109), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S97
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(110), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S98
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(17), // ), reduce: FunctionCall
			reduce(17), // ,, reduce: FunctionCall
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S99
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(18), // ), reduce: FunctionCall
			reduce(18), // ,, reduce: FunctionCall
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S100
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(20), // ), reduce: LambdaExpr
			reduce(20), // ,, reduce: LambdaExpr
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S101
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(112), // id
			nil,        // ::
			nil,        // =>
			shift(113), // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(115), // [
			nil,        // ]
			shift(118), // operations
			shift(119), // relop
			nil,        // #
			shift(121), // boolean
			shift(122), // number
			shift(123), // charac
		},
	},
	actionRow{ // S102
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			shift(124), // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S103
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			reduce(5), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S104
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(11), // ], reduce: Type
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S105
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(112), // id
			nil,        // ::
			nil,        // =>
			shift(113), // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(115), // [
			nil,        // ]
			shift(118), // operations
			shift(119), // relop
			nil,        // #
			shift(121), // boolean
			shift(122), // number
			shift(123), // charac
		},
	},
	actionRow{ // S106
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(16), // ,, reduce: FunctionCall
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(16), // ], reduce: FunctionCall
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S107
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(126), // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S108
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(17), // ,, reduce: FunctionCall
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(17), // ], reduce: FunctionCall
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S109
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(18), // ,, reduce: FunctionCall
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(18), // ], reduce: FunctionCall
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S110
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			reduce(20), // ,, reduce: LambdaExpr
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(20), // ], reduce: LambdaExpr
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S111
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(15), // ), reduce: Statement
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S112
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(127), // (
			reduce(12), // ), reduce: Statement
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S113
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			shift(128), // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S114
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(129), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S115
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(41),  // id
			nil,        // ::
			nil,        // =>
			shift(42),  // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(44),  // [
			reduce(24), // ], reduce: Args
			shift(48),  // operations
			shift(49),  // relop
			nil,        // #
			shift(51),  // boolean
			shift(52),  // number
			shift(53),  // charac
		},
	},
	actionRow{ // S116
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(13), // ), reduce: Statement
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S117
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(14), // ), reduce: Statement
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S118
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(131), // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S119
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(132), // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S120
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(133), // (
			reduce(19), // ), reduce: LambdaExpr
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S121
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(25), // ), reduce: Constant
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S122
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(26), // ), reduce: Constant
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S123
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(27), // ), reduce: Constant
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S124
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			reduce(11), // (, reduce: Type
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S125
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(134), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S126
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(112), // id
			nil,        // ::
			nil,        // =>
			shift(113), // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(115), // [
			nil,        // ]
			shift(118), // operations
			shift(119), // relop
			nil,        // #
			shift(121), // boolean
			shift(122), // number
			shift(123), // charac
		},
	},
	actionRow{ // S127
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S128
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			nil,       // func
			nil,       // id
			nil,       // ::
			reduce(7), // =>, reduce: Params
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			shift(33), // num
			shift(34), // bool
			shift(35), // char
			shift(36), // [
			nil,       // ]
			nil,       // operations
			nil,       // relop
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S129
		canRecover: false,
		actions: [numSymbols]action{
			nil,       // INVALID
			nil,       // $
			reduce(4), // func, reduce: Function
			reduce(4), // id, reduce: Function
			nil,       // ::
			nil,       // =>
			nil,       // (
			nil,       // )
			nil,       // ,
			nil,       // empty
			nil,       // num
			nil,       // bool
			nil,       // char
			nil,       // [
			nil,       // ]
			reduce(4), // operations, reduce: Function
			reduce(4), // relop, reduce: Function
			nil,       // #
			nil,       // boolean
			nil,       // number
			nil,       // charac
		},
	},
	actionRow{ // S130
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			shift(138), // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S131
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S132
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S133
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(16),  // id
			nil,        // ::
			nil,        // =>
			shift(17),  // (
			reduce(24), // ), reduce: Args
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(19),  // [
			nil,        // ]
			shift(23),  // operations
			shift(24),  // relop
			nil,        // #
			shift(26),  // boolean
			shift(27),  // number
			shift(28),  // charac
		},
	},
	actionRow{ // S134
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(142), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S135
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(143), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S136
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(144), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S137
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			shift(145), // =>
			nil,        // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S138
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(28), // ), reduce: Constant
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S139
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(146), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S140
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(147), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S141
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(148), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S142
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			reduce(21), // (, reduce: Lambda
			reduce(21), // ), reduce: Lambda
			reduce(21), // ,, reduce: Lambda
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S143
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(149), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S144
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(16), // ), reduce: FunctionCall
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S145
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			shift(150), // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S146
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(17), // ), reduce: FunctionCall
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S147
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(18), // ), reduce: FunctionCall
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S148
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			reduce(20), // ), reduce: LambdaExpr
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S149
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			reduce(21), // (, reduce: Lambda
			nil,        // )
			reduce(21), // ,, reduce: Lambda
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			reduce(21), // ], reduce: Lambda
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S150
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			shift(112), // id
			nil,        // ::
			nil,        // =>
			shift(113), // (
			nil,        // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			shift(115), // [
			nil,        // ]
			shift(118), // operations
			shift(119), // relop
			nil,        // #
			shift(121), // boolean
			shift(122), // number
			shift(123), // charac
		},
	},
	actionRow{ // S151
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(152), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S152
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			nil,        // (
			shift(153), // )
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
	actionRow{ // S153
		canRecover: false,
		actions: [numSymbols]action{
			nil,        // INVALID
			nil,        // $
			nil,        // func
			nil,        // id
			nil,        // ::
			nil,        // =>
			reduce(21), // (, reduce: Lambda
			reduce(21), // ), reduce: Lambda
			nil,        // ,
			nil,        // empty
			nil,        // num
			nil,        // bool
			nil,        // char
			nil,        // [
			nil,        // ]
			nil,        // operations
			nil,        // relop
			nil,        // #
			nil,        // boolean
			nil,        // number
			nil,        // charac
		},
	},
}
